/*---------------[BASIC QUERY]---------------*/

SELECT *
FROM CUSTOMER
WHERE ALAMAT = 'SUKABUMI';

SELECT NAMACUSTOMER, JENISKELAMIN, TGLLAHIR
FROM CUSTOMER ORDER BY TGLLAHIR;

SELECT NAMACUSTOMER, ALAMAT
FROM CUSTOMER
WHERE TGLLAHIR = '01-JAN-80';

/*---------------[JOIN QUERY]---------------*/

SELECT NAMACUSTOMER, TGLBERANGKAT
FROM TRANSAKSI JOIN KEBERANGKATAN USING(IDBERANGKAT) 
               JOIN PESAN USING(KODEPESANAN)
               JOIN CUSTOMER USING(IDCUSTOMER);

SELECT NAMACUSTOMER, JENISKELAMIN, NAMAPEMANDU, NOURUTKENDARAAN, NAMAHOTEL, NAMAFASILITAS, DESKRIPSI
FROM DAPAT JOIN FASILITAS USING(IDFASILITAS)
           JOIN KENDARAAN USING(IDFASILITAS)
           JOIN HOTEL USING(IDFASILITAS)
           JOIN PUNYA USING(IDFASILITAS)
           JOIN FASILITASHOTEL USING(IDFASILITASHOTEL)
           JOIN PEMANDU USING(IDPEMANDU)
           JOIN TRANSAKSI USING(NOTRANSAKSI)
           JOIN PESAN USING(KODEPESANAN)
           JOIN CUSTOMER USING(IDCUSTOMER)
WHERE IDCUSTOMER = 'CUS028';

/*------------[AGREGATE/SUBQUERY]------------*/

SELECT IDFASILITAS, KAPASITASJAMAAH
FROM FASILITAS
WHERE KAPASITASJAMAAH = (SELECT MAX(KAPASITASJAMAAH) FROM FASILITAS);

SELECT IDFASILITAS, KAPASITASJAMAAH
FROM FASILITAS
WHERE KAPASITASJAMAAH = (SELECT MIN(KAPASITASJAMAAH) FROM FASILITAS);

SELECT NAMACUSTOMER, JENISKELAMIN, ALAMAT, ROUND(MONTHS_BETWEEN(SYSDATE,TGLLAHIR)/12,0) USIA
FROM CUSTOMER
WHERE IDCUSTOMER = (SELECT IDCUSTOMER FROM CUSTOMER WHERE IDCUSTOMER = 'CUS029');

